version: "3.8"

services:
  # MongoDB Replica Set
  mongo:
    container_name: x-clone-mongo
    image: mongo:6.0
    ports:
      - 27018:27017
    command:
      - mongod
      - --replSet
      - rs0
      - --bind_ip_all
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongosh --quiet) -eq 1
      interval: 10s
      start_period: 30s

  # Redis
  redis:
    container_name: x-clone-redis
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  redis_data:
